# Generated by Django 5.1.1 on 2024-10-08 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ful_name', models.CharField(max_length=100)),
                ('nambr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=200)),
                ('ful_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Our_partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Our_programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Why_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('contact_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contact_us')),
            ],
        ),
        migrations.CreateModel(
            name='computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protssesor', models.CharField(max_length=200)),
                ('Cpu', models.CharField(max_length=200)),
                ('video_karta', models.CharField(max_length=200)),
                ('ekran', models.CharField(max_length=200)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('ful_name', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Faq_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.faq')),
            ],
        ),
        migrations.CreateModel(
            name='For_whom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('description', models.TextField()),
                ('mentors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mentors')),
            ],
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_n', models.CharField(max_length=200)),
                ('description_n', models.TextField()),
                ('title_a', models.CharField(max_length=200)),
                ('description_a', models.TextField()),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('our_partners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.our_partners')),
            ],
        ),
    ]
