# Generated by Django 5.1.1 on 2024-10-08 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='contact_us',
        ),
        migrations.AddField(
            model_name='contact_us',
            name='courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.courses'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Places_of_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ikonka', models.ImageField(upload_to='media/')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mentor')),
            ],
        ),
    ]
