# Generated by Django 5.1.1 on 2024-10-10 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lessons_remove_comment_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='title_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='title_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='Cpu_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='Cpu_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='Cpu_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='ekran_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='ekran_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='ekran_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='protssesor_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='protssesor_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='protssesor_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='video_karta_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='video_karta_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='video_karta_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact_us',
            name='ischecked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='for_whom',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='for_whom',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='for_whom',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='for_whom',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='for_whom',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='for_whom',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='lesson_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='lesson_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='lesson_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='modul',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.modul'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentors',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mentors',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mentors',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='modul',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='modul',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='modul',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='our_programs',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='our_programs',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='our_programs',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='our_programs',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='our_programs',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='our_programs',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_a_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_a_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_a_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_n_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_n_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_n_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title_a_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title_a_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title_a_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title_n_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title_n_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title_n_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='why_us',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='why_us',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='why_us',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='why_us',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='why_us',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='why_us',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='lesson',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Faq_desc',
        ),
    ]
